// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/rpc.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LnurlWithdrawRequest struct {
	// Types that are valid to be assigned to Event:
	//	*LnurlWithdrawRequest_Open
	//	*LnurlWithdrawRequest_Pay
	Event                isLnurlWithdrawRequest_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *LnurlWithdrawRequest) Reset()         { *m = LnurlWithdrawRequest{} }
func (m *LnurlWithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*LnurlWithdrawRequest) ProtoMessage()    {}
func (*LnurlWithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0518e1b3743dbf2, []int{0}
}

func (m *LnurlWithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LnurlWithdrawRequest.Unmarshal(m, b)
}
func (m *LnurlWithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LnurlWithdrawRequest.Marshal(b, m, deterministic)
}
func (m *LnurlWithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LnurlWithdrawRequest.Merge(m, src)
}
func (m *LnurlWithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_LnurlWithdrawRequest.Size(m)
}
func (m *LnurlWithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LnurlWithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LnurlWithdrawRequest proto.InternalMessageInfo

type isLnurlWithdrawRequest_Event interface {
	isLnurlWithdrawRequest_Event()
}

type LnurlWithdrawRequest_Open struct {
	Open *OpenWithdraw `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type LnurlWithdrawRequest_Pay struct {
	Pay *PayResponse `protobuf:"bytes,2,opt,name=pay,proto3,oneof"`
}

func (*LnurlWithdrawRequest_Open) isLnurlWithdrawRequest_Event() {}

func (*LnurlWithdrawRequest_Pay) isLnurlWithdrawRequest_Event() {}

func (m *LnurlWithdrawRequest) GetEvent() isLnurlWithdrawRequest_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *LnurlWithdrawRequest) GetOpen() *OpenWithdraw {
	if x, ok := m.GetEvent().(*LnurlWithdrawRequest_Open); ok {
		return x.Open
	}
	return nil
}

func (m *LnurlWithdrawRequest) GetPay() *PayResponse {
	if x, ok := m.GetEvent().(*LnurlWithdrawRequest_Pay); ok {
		return x.Pay
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LnurlWithdrawRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LnurlWithdrawRequest_Open)(nil),
		(*LnurlWithdrawRequest_Pay)(nil),
	}
}

type LnurlWithdrawResponse struct {
	// Types that are valid to be assigned to Event:
	//	*LnurlWithdrawResponse_BechString
	//	*LnurlWithdrawResponse_Invoice
	Event                isLnurlWithdrawResponse_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *LnurlWithdrawResponse) Reset()         { *m = LnurlWithdrawResponse{} }
func (m *LnurlWithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*LnurlWithdrawResponse) ProtoMessage()    {}
func (*LnurlWithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0518e1b3743dbf2, []int{1}
}

func (m *LnurlWithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LnurlWithdrawResponse.Unmarshal(m, b)
}
func (m *LnurlWithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LnurlWithdrawResponse.Marshal(b, m, deterministic)
}
func (m *LnurlWithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LnurlWithdrawResponse.Merge(m, src)
}
func (m *LnurlWithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_LnurlWithdrawResponse.Size(m)
}
func (m *LnurlWithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LnurlWithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LnurlWithdrawResponse proto.InternalMessageInfo

type isLnurlWithdrawResponse_Event interface {
	isLnurlWithdrawResponse_Event()
}

type LnurlWithdrawResponse_BechString struct {
	BechString *LnurlString `protobuf:"bytes,1,opt,name=bech_string,json=bechString,proto3,oneof"`
}

type LnurlWithdrawResponse_Invoice struct {
	Invoice *Invoice `protobuf:"bytes,2,opt,name=invoice,proto3,oneof"`
}

func (*LnurlWithdrawResponse_BechString) isLnurlWithdrawResponse_Event() {}

func (*LnurlWithdrawResponse_Invoice) isLnurlWithdrawResponse_Event() {}

func (m *LnurlWithdrawResponse) GetEvent() isLnurlWithdrawResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *LnurlWithdrawResponse) GetBechString() *LnurlString {
	if x, ok := m.GetEvent().(*LnurlWithdrawResponse_BechString); ok {
		return x.BechString
	}
	return nil
}

func (m *LnurlWithdrawResponse) GetInvoice() *Invoice {
	if x, ok := m.GetEvent().(*LnurlWithdrawResponse_Invoice); ok {
		return x.Invoice
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LnurlWithdrawResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LnurlWithdrawResponse_BechString)(nil),
		(*LnurlWithdrawResponse_Invoice)(nil),
	}
}

type OpenWithdraw struct {
	WithdrawId           string   `protobuf:"bytes,1,opt,name=withdraw_id,json=withdrawId,proto3" json:"withdraw_id,omitempty"`
	MinAmount            int64    `protobuf:"varint,2,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount            int64    `protobuf:"varint,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenWithdraw) Reset()         { *m = OpenWithdraw{} }
func (m *OpenWithdraw) String() string { return proto.CompactTextString(m) }
func (*OpenWithdraw) ProtoMessage()    {}
func (*OpenWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0518e1b3743dbf2, []int{2}
}

func (m *OpenWithdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenWithdraw.Unmarshal(m, b)
}
func (m *OpenWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenWithdraw.Marshal(b, m, deterministic)
}
func (m *OpenWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenWithdraw.Merge(m, src)
}
func (m *OpenWithdraw) XXX_Size() int {
	return xxx_messageInfo_OpenWithdraw.Size(m)
}
func (m *OpenWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_OpenWithdraw proto.InternalMessageInfo

func (m *OpenWithdraw) GetWithdrawId() string {
	if m != nil {
		return m.WithdrawId
	}
	return ""
}

func (m *OpenWithdraw) GetMinAmount() int64 {
	if m != nil {
		return m.MinAmount
	}
	return 0
}

func (m *OpenWithdraw) GetMaxAmount() int64 {
	if m != nil {
		return m.MaxAmount
	}
	return 0
}

func (m *OpenWithdraw) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type PayResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayResponse) Reset()         { *m = PayResponse{} }
func (m *PayResponse) String() string { return proto.CompactTextString(m) }
func (*PayResponse) ProtoMessage()    {}
func (*PayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0518e1b3743dbf2, []int{3}
}

func (m *PayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResponse.Unmarshal(m, b)
}
func (m *PayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResponse.Marshal(b, m, deterministic)
}
func (m *PayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResponse.Merge(m, src)
}
func (m *PayResponse) XXX_Size() int {
	return xxx_messageInfo_PayResponse.Size(m)
}
func (m *PayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayResponse proto.InternalMessageInfo

func (m *PayResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PayResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type LnurlString struct {
	BechString           string   `protobuf:"bytes,1,opt,name=bech_string,json=bechString,proto3" json:"bech_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LnurlString) Reset()         { *m = LnurlString{} }
func (m *LnurlString) String() string { return proto.CompactTextString(m) }
func (*LnurlString) ProtoMessage()    {}
func (*LnurlString) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0518e1b3743dbf2, []int{4}
}

func (m *LnurlString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LnurlString.Unmarshal(m, b)
}
func (m *LnurlString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LnurlString.Marshal(b, m, deterministic)
}
func (m *LnurlString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LnurlString.Merge(m, src)
}
func (m *LnurlString) XXX_Size() int {
	return xxx_messageInfo_LnurlString.Size(m)
}
func (m *LnurlString) XXX_DiscardUnknown() {
	xxx_messageInfo_LnurlString.DiscardUnknown(m)
}

var xxx_messageInfo_LnurlString proto.InternalMessageInfo

func (m *LnurlString) GetBechString() string {
	if m != nil {
		return m.BechString
	}
	return ""
}

type Invoice struct {
	Invoice              string   `protobuf:"bytes,1,opt,name=Invoice,proto3" json:"Invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0518e1b3743dbf2, []int{5}
}

func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (m *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(m, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetInvoice() string {
	if m != nil {
		return m.Invoice
	}
	return ""
}

func init() {
	proto.RegisterType((*LnurlWithdrawRequest)(nil), "api.LnurlWithdrawRequest")
	proto.RegisterType((*LnurlWithdrawResponse)(nil), "api.LnurlWithdrawResponse")
	proto.RegisterType((*OpenWithdraw)(nil), "api.OpenWithdraw")
	proto.RegisterType((*PayResponse)(nil), "api.PayResponse")
	proto.RegisterType((*LnurlString)(nil), "api.LnurlString")
	proto.RegisterType((*Invoice)(nil), "api.Invoice")
}

func init() { proto.RegisterFile("api/rpc.proto", fileDescriptor_a0518e1b3743dbf2) }

var fileDescriptor_a0518e1b3743dbf2 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x4f, 0xe3, 0x30,
	0x10, 0x4d, 0x36, 0xdd, 0x56, 0x99, 0xb4, 0xd2, 0xae, 0xb5, 0xbb, 0xca, 0x56, 0x5a, 0x6d, 0x15,
	0x90, 0xe8, 0x29, 0xa0, 0xf6, 0xcc, 0x01, 0x4e, 0x29, 0x42, 0xa2, 0x32, 0x07, 0x0e, 0x1c, 0x2a,
	0x37, 0xb1, 0xa8, 0x25, 0x6a, 0x1b, 0xdb, 0xe9, 0xc7, 0x89, 0x9f, 0xc0, 0x5f, 0x46, 0x71, 0x1c,
	0x1a, 0x2a, 0x6e, 0x9e, 0xf7, 0x9e, 0x3d, 0x6f, 0x9e, 0x07, 0x06, 0x44, 0xb2, 0x73, 0x25, 0xf3,
	0x54, 0x2a, 0x61, 0x04, 0x0a, 0x88, 0x64, 0x09, 0x87, 0x5f, 0xb7, 0xbc, 0x54, 0xcf, 0x0f, 0xcc,
	0xac, 0x0a, 0x45, 0xb6, 0x98, 0xbe, 0x94, 0x54, 0x1b, 0x74, 0x06, 0x1d, 0x21, 0x29, 0x8f, 0xfd,
	0x91, 0x3f, 0x8e, 0x26, 0x3f, 0x53, 0x22, 0x59, 0x7a, 0x27, 0x29, 0x6f, 0x74, 0x99, 0x87, 0xad,
	0x00, 0x9d, 0x42, 0x20, 0xc9, 0x3e, 0xfe, 0x66, 0x75, 0x3f, 0xac, 0x6e, 0x4e, 0xf6, 0x98, 0x6a,
	0x29, 0xb8, 0xa6, 0x99, 0x87, 0x2b, 0xfa, 0xba, 0x07, 0xdf, 0xe9, 0x86, 0x72, 0x93, 0xbc, 0xc2,
	0xef, 0xa3, 0x7e, 0xb5, 0x10, 0x4d, 0x21, 0x5a, 0xd2, 0x7c, 0xb5, 0xd0, 0x46, 0x31, 0xfe, 0xe4,
	0xfa, 0xd6, 0xef, 0xd9, 0x0b, 0xf7, 0x16, 0xcf, 0x3c, 0x0c, 0x95, 0xac, 0xae, 0xd0, 0x18, 0x7a,
	0x8c, 0x6f, 0x04, 0xcb, 0xa9, 0x33, 0xd0, 0xb7, 0x17, 0x66, 0x35, 0x96, 0x79, 0xb8, 0xa1, 0x0f,
	0x06, 0xde, 0x7c, 0xe8, 0xb7, 0x07, 0x41, 0xff, 0x21, 0xda, 0xba, 0xf3, 0x82, 0x15, 0xb6, 0x71,
	0x88, 0xa1, 0x81, 0x66, 0x05, 0xfa, 0x07, 0xb0, 0x66, 0x7c, 0x41, 0xd6, 0xa2, 0xe4, 0xc6, 0xf6,
	0x09, 0x70, 0xb8, 0x66, 0xfc, 0xca, 0x02, 0x96, 0x26, 0xbb, 0x86, 0x0e, 0x1c, 0x4d, 0x76, 0x8e,
	0x1e, 0x41, 0x54, 0x50, 0x9d, 0x2b, 0x26, 0x0d, 0x13, 0x3c, 0xee, 0xd8, 0xe7, 0xdb, 0x50, 0x72,
	0x09, 0x51, 0x2b, 0x31, 0xf4, 0x07, 0xba, 0xda, 0x10, 0x53, 0x6a, 0x67, 0xc5, 0x55, 0x15, 0xae,
	0x28, 0xd1, 0x82, 0x5b, 0x0b, 0x21, 0x76, 0x55, 0x92, 0x42, 0xd4, 0x0a, 0xa8, 0x1a, 0xe7, 0x38,
	0xc7, 0xb0, 0x9d, 0x59, 0x72, 0x02, 0x3d, 0x97, 0x0f, 0x8a, 0x3f, 0x8e, 0x4e, 0xd7, 0x94, 0x93,
	0x47, 0x18, 0x34, 0x01, 0xcd, 0x95, 0xd8, 0xed, 0xd1, 0x0d, 0x0c, 0x3e, 0xfd, 0x1b, 0xfa, 0x7b,
	0xf8, 0x9a, 0xa3, 0xdd, 0x19, 0x0e, 0xbf, 0xa2, 0xea, 0xe9, 0xc6, 0xfe, 0x85, 0xbf, 0xec, 0xda,
	0xfd, 0x9b, 0xbe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x59, 0xb5, 0x24, 0x1a, 0x90, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WithdrawProxyClient is the client API for WithdrawProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WithdrawProxyClient interface {
	LnurlWithdraw(ctx context.Context, opts ...grpc.CallOption) (WithdrawProxy_LnurlWithdrawClient, error)
}

type withdrawProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewWithdrawProxyClient(cc grpc.ClientConnInterface) WithdrawProxyClient {
	return &withdrawProxyClient{cc}
}

func (c *withdrawProxyClient) LnurlWithdraw(ctx context.Context, opts ...grpc.CallOption) (WithdrawProxy_LnurlWithdrawClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WithdrawProxy_serviceDesc.Streams[0], "/api.WithdrawProxy/LnurlWithdraw", opts...)
	if err != nil {
		return nil, err
	}
	x := &withdrawProxyLnurlWithdrawClient{stream}
	return x, nil
}

type WithdrawProxy_LnurlWithdrawClient interface {
	Send(*LnurlWithdrawRequest) error
	Recv() (*LnurlWithdrawResponse, error)
	grpc.ClientStream
}

type withdrawProxyLnurlWithdrawClient struct {
	grpc.ClientStream
}

func (x *withdrawProxyLnurlWithdrawClient) Send(m *LnurlWithdrawRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *withdrawProxyLnurlWithdrawClient) Recv() (*LnurlWithdrawResponse, error) {
	m := new(LnurlWithdrawResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WithdrawProxyServer is the server API for WithdrawProxy service.
type WithdrawProxyServer interface {
	LnurlWithdraw(WithdrawProxy_LnurlWithdrawServer) error
}

// UnimplementedWithdrawProxyServer can be embedded to have forward compatible implementations.
type UnimplementedWithdrawProxyServer struct {
}

func (*UnimplementedWithdrawProxyServer) LnurlWithdraw(srv WithdrawProxy_LnurlWithdrawServer) error {
	return status.Errorf(codes.Unimplemented, "method LnurlWithdraw not implemented")
}

func RegisterWithdrawProxyServer(s *grpc.Server, srv WithdrawProxyServer) {
	s.RegisterService(&_WithdrawProxy_serviceDesc, srv)
}

func _WithdrawProxy_LnurlWithdraw_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WithdrawProxyServer).LnurlWithdraw(&withdrawProxyLnurlWithdrawServer{stream})
}

type WithdrawProxy_LnurlWithdrawServer interface {
	Send(*LnurlWithdrawResponse) error
	Recv() (*LnurlWithdrawRequest, error)
	grpc.ServerStream
}

type withdrawProxyLnurlWithdrawServer struct {
	grpc.ServerStream
}

func (x *withdrawProxyLnurlWithdrawServer) Send(m *LnurlWithdrawResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *withdrawProxyLnurlWithdrawServer) Recv() (*LnurlWithdrawRequest, error) {
	m := new(LnurlWithdrawRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _WithdrawProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WithdrawProxy",
	HandlerType: (*WithdrawProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LnurlWithdraw",
			Handler:       _WithdrawProxy_LnurlWithdraw_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/rpc.proto",
}
